# Generated by Django 4.1 on 2023-04-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sucursal',
            new_name='Sucursale',
        ),
    ]
