# Generated by Django 4.1 on 2023-04-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientes', '0002_rename_sucursal_sucursale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursale',
            name='ciudad',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
