# Generated by Django 4.1 on 2023-04-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientes', '0004_alter_sucursale_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sucursale',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
