# Generated by Django 4.2 on 2023-04-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientes', '0007_mensajero_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='propietarioCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionClientes.cliente'),
        ),
        migrations.AlterField(
            model_name='user',
            name='propietarioMensajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionClientes.mensajero'),
        ),
    ]
