# Generated by Django 4.2 on 2023-04-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientes', '0008_alter_user_propietariocliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='propietarioCliente',
        ),
        migrations.RemoveField(
            model_name='user',
            name='propietarioMensajero',
        ),
        migrations.DeleteModel(
            name='Mensajero',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
