name: Docker

on:
  push:
    branches: [main]

env:
  IMAGE_TAG: miche890/king-courier:latest-${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login a DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Crear imagen de Docker
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}

      - name: Subir imagen a DockerHub
        run: docker push ${{ env.IMAGE_TAG }}
